const CATEGORIES = [
  { name: "technology", color: "#3b82f6" },
  { name: "society", color: "#eab308" },
  { name: "science", color: "#16a34a" },
  { name: "finance", color: "#ef4444" },
  { name: "history", color: "#f97316" },
  { name: "entertainment", color: "#db2777" },
  { name: "health", color: "#14b8a6" },
  { name: "news", color: "#8b5cf6" },
];

const initialFacts = [
  {
    id: 1,
    text: "React is being developed by Meta (formerly Facebook)",
    source: "https://opensource.fb.com/",
    category: "technology",
    votesInteresting: 24,
    votesMindblowing: 9,
    votesFalse: 4,
    createdIn: 2021,
  },
  {
    id: 2,
    text: "Millennial dads spend 3 times as much time with their kids than their fathers did.",
    source:
      "https://www.mother.ly/parenting/millennial-dads-spend-more-time-with-their-kids",
    category: "society",
    votesInteresting: 11,
    votesMindblowing: 2,
    votesFalse: 0,
    createdIn: 2019,
  },
  {
    id: 3,
    text: "Lisbon is the capital of Portugal.",
    source: "https://en.wikipedia.org/wiki/Lisbon",
    category: "society",
    votesInteresting: 8,
    votesMindblowing: 3,
    votesFalse: 1,
    createdIn: 2015,
  },
  {
    id: 4,
    text: "JavaScript was created in just 10 days in 1995.",
    source: "https://developer.mozilla.org/en-US/docs/Web/JavaScript",
    category: "technology",
    votesInteresting: 32,
    votesMindblowing: 15,
    votesFalse: 2,
    createdIn: 1995,
  },
  {
    id: 5,
    text: "The human body contains around 37.2 trillion cells.",
    source: "https://www.scientificamerican.com/",
    category: "science",
    votesInteresting: 40,
    votesMindblowing: 20,
    votesFalse: 1,
    createdIn: 2013,
  },
  {
    id: 6,
    text: "Bitcoin was created in 2009 by an unknown person using the name Satoshi Nakamoto.",
    source: "https://bitcoin.org/en/",
    category: "finance",
    votesInteresting: 21,
    votesMindblowing: 11,
    votesFalse: 3,
    createdIn: 2009,
  },
  {
    id: 7,
    text: "The Eiffel Tower can be 15 cm taller during summer due to metal expansion.",
    source: "https://www.toureiffel.paris/",
    category: "science",
    votesInteresting: 12,
    votesMindblowing: 6,
    votesFalse: 1,
    createdIn: 2012,
  },
  {
    id: 8,
    text: "The first email was sent by Ray Tomlinson to himself in 1971.",
    source: "https://www.history.com/",
    category: "technology",
    votesInteresting: 18,
    votesMindblowing: 4,
    votesFalse: 0,
    createdIn: 1971,
  },
  {
    id: 9,
    text: "In ancient Rome, urine was used as mouthwash due to its ammonia content.",
    source: "https://www.nationalgeographic.com/",
    category: "history",
    votesInteresting: 28,
    votesMindblowing: 30,
    votesFalse: 2,
    createdIn: -50,
  },
  {
    id: 10,
    text: "About 90% of the world’s data was created in the last two years.",
    source: "https://www.forbes.com/",
    category: "technology",
    votesInteresting: 35,
    votesMindblowing: 22,
    votesFalse: 5,
    createdIn: 2020,
  },
  {
    id: 11,
    text: "Sharks existed before trees — they appeared over 400 million years ago.",
    source: "https://ocean.si.edu/",
    category: "science",
    votesInteresting: 26,
    votesMindblowing: 18,
    votesFalse: 1,
    createdIn: -400000000,
  },
  {
    id: 12,
    text: "Apple became the first U.S. company to reach a $3 trillion market cap.",
    source: "https://www.cnbc.com/",
    category: "finance",
    votesInteresting: 29,
    votesMindblowing: 7,
    votesFalse: 0,
    createdIn: 2022,
  },
  {
    id: 13,
    text: "Netflix was founded in 1997 as a DVD rental service.",
    source: "https://about.netflix.com/",
    category: "entertainment",
    votesInteresting: 17,
    votesMindblowing: 5,
    votesFalse: 0,
    createdIn: 1997,
  },
  {
    id: 14,
    text: "Your stomach gets a new lining every 3 to 4 days to prevent digesting itself.",
    source: "https://www.ncbi.nlm.nih.gov/",
    category: "health",
    votesInteresting: 22,
    votesMindblowing: 13,
    votesFalse: 0,
    createdIn: 2011,
  },
  {
    id: 15,
    text: "Cleopatra lived closer to the iPhone than to the building of the pyramids.",
    source: "https://www.historyextra.com/",
    category: "history",
    votesInteresting: 37,
    votesMindblowing: 26,
    votesFalse: 3,
    createdIn: -30,
  },
  {
    id: 16,
    text: "There are more trees on Earth than stars in the Milky Way galaxy.",
    source: "https://www.nature.com/",
    category: "science",
    votesInteresting: 33,
    votesMindblowing: 19,
    votesFalse: 2,
    createdIn: 2015,
  },
  {
    id: 17,
    text: "Only 8% of the world’s currency exists as physical cash.",
    source: "https://www.investopedia.com/",
    category: "finance",
    votesInteresting: 30,
    votesMindblowing: 17,
    votesFalse: 0,
    createdIn: 2020,
  },
  {
    id: 18,
    text: "Humans share around 60% of their DNA with bananas.",
    source: "https://genetics.thetech.org/",
    category: "science",
    votesInteresting: 34,
    votesMindblowing: 23,
    votesFalse: 5,
    createdIn: 2005,
  },
  {
    id: 19,
    text: "The news outlet BBC first aired in 1922.",
    source: "https://www.bbc.com/historyofthebbc",
    category: "news",
    votesInteresting: 16,
    votesMindblowing: 6,
    votesFalse: 0,
    createdIn: 1922,
  },
  {
    id: 20,
    text: "Your brain uses around 20% of your body's total energy.",
    source: "https://www.ncbi.nlm.nih.gov/",
    category: "health",
    votesInteresting: 25,
    votesMindblowing: 10,
    votesFalse: 1,
    createdIn: 2007,
  },
];
